---
- name: Exercise 2
  hosts: local
  tasks:
  - name: Register hostname in Var
    local_action: command hostname
    register: hostname

  - debug: msg={{ hostname.stdout }}

  - name: Build image from dockerfile directory
    docker_image:
      path: ./sshDocker
      name: playbooksshimage

  - name: Create a container which have sshd and nginx
    docker_container:
      name: playbookssh
      image: playbooksshimage
      ports:
        - "10080:80"
        - "10022:22"
